- name: Install baseline packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - bind-utils
    - epel-release
    - git
    - htop
    - ncdu
    - python-pip
    - tmux
    - tree
    - vim
    - wget
