- name: Add authorized key to centos user
  authorized_key:
    user: centos
    key: "{{ item }}"
    state: present
  with_file:
    - files/ssh/public_keys/bueno
    - files/ssh/public_keys/fagoaga
    - files/ssh/public_keys/faltin
    - files/ssh/public_keys/fraundorfer
    - files/ssh/public_keys/grimme
    - files/ssh/public_keys/guiteras
    - files/ssh/public_keys/ignacz
    - files/ssh/public_keys/jenkins
    - files/ssh/public_keys/kobara
    - files/ssh/public_keys/lopez
    - files/ssh/public_keys/marjanovic
    - files/ssh/public_keys/meyer
    - files/ssh/public_keys/mujkic
    - files/ssh/public_keys/munteanu
    - files/ssh/public_keys/neumayr
    - files/ssh/public_keys/romagosa
    - files/ssh/public_keys/shihadeh
    - files/ssh/public_keys/yedes

- name: Add private key to centos user
  copy:
    src: ssh/private_keys/id_rsa
    dest: /home/centos/.ssh/id_rsa
    mode: 0600
    owner: centos
