-
  hosts: all
  tasks:
  - name: install baseline packages
    package:
      name: "{{ item }}"
      state: present
    with_items:
    - bind-utils
    - epel-release
    - htop
    - ncdu
    - tmux
    - vim
    - git
