- name: Baseline
  hosts: all
  become: yes
  roles:
    - baseline

- name: Docker
  hosts: docker
  become: yes
  roles:
    - docker

- name: Docker Swarm
  hosts: docker-swarm-master
  become: yes
  roles:
    - docker-swarm-master
