- name: Configure docker service
  copy:
    dest: /etc/docker/daemon.json
    content: '{ "insecure-registries" : [ "docker-prod.fidor.intern:5000" ] }'
  register: daemon_json

- name: Enable and start docker service
  systemd:
    name: docker
    state: restarted
    enabled: yes
  when: daemon_json.changed
