- name: Ensure bin folder exists
  file:
    path: /home/centos/bin
    state: directory
    owner: centos
    group: centos

- name: Install dtools script
  get_url:
    url: https://gist.githubusercontent.com/klausmeyer/c699828e178ffa6817ccd44f3f32dcda/raw/a8f1d8f9b2b70512b767df53f5cc0e38b23145d8/dtools
    dest: /home/centos/bin/dtools
    owner: centos
    group: centos
    mode: 0744
