- name: Add docker YUM repo
  yum_repository:
    name: docker-main-repo
    description: Docker main Repository
    baseurl: https://download.docker.com/linux/centos/7/x86_64/stable
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: Install docker package
  yum:
    name: docker-ce-17.12.0.ce-1.el7.centos
    state: present

- name: Enable docker service
  systemd:
    name: docker
    state: started

- name: Add centos user to docker group
  user:
    name: centos
    groups: docker
